/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/office_desk.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Monitor_ScreenGlass: THREE.Mesh
    Object_18: THREE.Mesh
    Object_26: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_75: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_101: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    HouseFloor: THREE.Mesh
    HouseWall_Back: THREE.Mesh
    Baseboard_Back: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Monitor_Chassis: THREE.Mesh
  }
  materials: {
    M_Cactus_1024: THREE.MeshStandardMaterial
    M_ScreenGlass: THREE.MeshStandardMaterial
    M_Filebox_1024: THREE.MeshStandardMaterial
    M_Office_PinBoard_Photo_Notepad_1024: THREE.MeshStandardMaterial
    M_Table_2048: THREE.MeshStandardMaterial
    M_TapeRecorder_1024: THREE.MeshStandardMaterial
    M_TapeRecorder_Tape_Rotors_Glass_1024: THREE.MeshStandardMaterial
    M_Vent_1024: THREE.MeshStandardMaterial
    Poster_1024: THREE.MeshStandardMaterial
    PhotoFrame_20x30_likeA4_512: THREE.MeshStandardMaterial
    M_Clipboard_Notepad_1024: THREE.MeshStandardMaterial
    M_OfficeStool_Bin_2048: THREE.MeshStandardMaterial
    ['M_Lamps_CCTV_2048.001']: THREE.MeshStandardMaterial
    M_HouseFloor: THREE.MeshStandardMaterial
    M_HouseWall: THREE.MeshStandardMaterial
    M_Baseboard: THREE.MeshStandardMaterial
    ['hanging_picture_frame_01_artwork.005']: THREE.MeshStandardMaterial
    ['hanging_picture_frame_01.005']: THREE.MeshStandardMaterial
    M_Computer_2048: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/office_desk.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.M_Cactus_1024} position={[0.278, 1.169, 1.092]} rotation={[0, -0.736, 0]} scale={0.578} />
      <mesh geometry={nodes.Monitor_ScreenGlass.geometry} material={materials.M_ScreenGlass} position={[0.589, 1.169, 1.121]} rotation={[0, 0.168, 0]} scale={0.578} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.M_Filebox_1024} position={[0.259, 1.169, 1.328]} rotation={[0, 1.531, 0]} scale={[0.634, 0.578, 0.578]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.517, 1.169, 1.593]} rotation={[-0.005, 1.388, 0.005]} scale={[0.22, 0.079, 0.22]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.M_Table_2048} position={[0.431, 0.742, 1.263]} scale={0.578} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.M_TapeRecorder_1024} position={[0.327, 1.169, 1.686]} rotation={[-Math.PI, 1.358, -Math.PI]} scale={0.578} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} position={[0.327, 1.169, 1.686]} rotation={[-Math.PI, 1.358, -Math.PI]} scale={0.578} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.M_Vent_1024} position={[0.18, 1.9, 1.8]} scale={0.578} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Poster_1024} position={[0.165, 1.645, 1.347]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.358, 0.179, 0.358]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.PhotoFrame_20x30_likeA4_512} position={[0.168, 1.473, 0.53]} rotation={[0, -1.571, 0]} scale={[0.574, 0.574, 0.646]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.883, 1.066, 0.944]} rotation={[-3.126, -1.002, -1.576]} scale={0.578} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.M_OfficeStool_Bin_2048} position={[0.841, 0.744, 1.031]} rotation={[Math.PI, -0.416, Math.PI]} scale={[0.714, 0.578, 0.714]} />
      <mesh geometry={nodes.Object_109.geometry} material={materials['M_Lamps_CCTV_2048.001']} position={[0.285, 1.169, 1.49]} rotation={[0, 0.454, 0]} scale={0.578} />
      <mesh geometry={nodes.HouseFloor.geometry} material={materials.M_HouseFloor} position={[0.308, 0.739, 1.164]} scale={0.578} />
      <mesh geometry={nodes.HouseWall_Back.geometry} material={materials.M_HouseWall} position={[0.163, 6.521, 1.164]} rotation={[0, 0, -Math.PI / 2]} scale={0.578} />
      <mesh geometry={nodes.Baseboard_Back.geometry} material={materials.M_Baseboard} position={[0.175, 0.768, 1.164]} scale={[0.012, 0.058, 11.564]} />
      <group position={[0.175, 1.5, 0.276]} rotation={[0, Math.PI / 2, 0]} scale={0.3}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['hanging_picture_frame_01_artwork.005']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['hanging_picture_frame_01.005']} />
      </group>
      <mesh geometry={nodes.Monitor_Chassis.geometry} material={materials.M_Computer_2048} position={[0.589, 1.169, 1.121]} rotation={[0, 0.168, 0]} scale={0.578} />
    </group>
  )
}

useGLTF.preload('/office_desk.glb')
